// Pi live binding through a per-spawn extension.
//
// Pi owns its session id and can switch it in-place (/new, /resume, /fork). The core already has a
// backend-neutral terminal binding URL for "terminal <tag> is now on session <id>" (#303); this adapter
// writes a tiny Pi extension that posts that fact on session lifecycle events. Pi-specific event names and
// ctx.sessionManager access stay here, under the backend descriptor.
//
// **Waiting is not working** (#529). Pi 0.84.4 added `ui_prompt_start` / `ui_prompt_end`, which separate
// active agent work from time spent blocked on a `ctx.ui` prompt. Without them the two are one state and
// a session sat on "Working" while it was actually holding a question nobody had seen — the row said the
// agent was busy, and the inbox said nothing at all. `ui_prompt_end` reports `busy` rather than `idle`
// because answering a prompt returns the agent to the turn it was in the middle of; the turn's own
// `turn_end` / `agent_settled` still ends it.
//
// The prompt's TITLE is deliberately not sent. It is arbitrary text from whatever the agent happens to be
// running, and it would be rendered in the attention inbox; the prompt KIND is a closed set
// (select / confirm / input / editor / custom) and says enough to word the reason. The wording itself is
// `shared/attention-source.js`, with every other source's.
//
// **KNOW WHAT THIS COVERS, measured in Pi 0.84.4's own bundle.** The events are emitted by `withUIPrompt`,
// which wraps only the UI context handed to EXTENSIONS — `ctx.ui.select/confirm/input/editor/custom`. Pi's
// own dialogs do not go through it, so a tool-permission prompt or a model picker raises nothing here.
// What this reports is a session blocked on a prompt some extension opened, which is a real state and
// costs two lines to report, but it is not "any Pi session waiting for you". Do not read a quiet inbox as
// proof the binding is broken, and do not extend this by guessing at Pi's internal dialogs: the only
// honest widening is an event Pi emits for them.
//
// Also measured: in `--print` mode the whole UI context is a no-op stub, `confirm` returns immediately and
// no event is emitted at all. These fire in the interactive TUI, which is the mode Switchboard spawns.
'use strict';

const fs = require('fs');
const path = require('path');

function jsString(value) {
  return JSON.stringify(String(value || ''));
}

function writeBindingExtension({ dir, tag, sessionUrl, log } = {}) {
  if (!dir || !tag || !sessionUrl) return null;
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `pi-live-${tag}.ts`);
  const source = `// Generated by Switchboard for one Pi spawn. Safe to delete.\n` +
`import type { ExtensionAPI } from \"@earendil-works/pi-coding-agent\";\n\n` +
`const URL = ${jsString(sessionUrl)};\n\n` +
`async function post(ctx: any, kind?: \"busy\" | \"idle\" | \"waiting\", promptKind?: string) {\n` +
`  const id = ctx?.sessionManager?.getSessionId?.();\n` +
`  if (!id) return;\n` +
`  try {\n` +
`    await fetch(URL, {\n` +
`      method: \"POST\",\n` +
`      headers: { \"content-type\": \"application/json\" },\n` +
`      body: JSON.stringify({ session_id: id, kind, prompt_kind: promptKind }),\n` +
`    });\n` +
`  } catch {}\n` +
`}\n\n` +
`export default function(pi: ExtensionAPI) {\n` +
`  pi.on(\"session_start\", async (_event, ctx) => { await post(ctx); });\n` +
`  pi.on(\"turn_start\", async (_event, ctx) => { await post(ctx, \"busy\"); });\n` +
`  pi.on(\"ui_prompt_start\", async (event: any, ctx) => { await post(ctx, \"waiting\", event?.kind); });\n` +
`  pi.on(\"ui_prompt_end\", async (_event, ctx) => { await post(ctx, \"busy\"); });\n` +
`  pi.on(\"turn_end\", async (_event, ctx) => { await post(ctx, \"idle\"); });\n` +
`  pi.on(\"agent_settled\", async (_event, ctx) => { await post(ctx, \"idle\"); });\n` +
`  pi.on(\"session_info_changed\", async (_event, ctx) => { await post(ctx); });\n` +
`}\n`;
  fs.writeFileSync(file, source, 'utf8');
  if (log && typeof log.debug === 'function') log.debug(`[pi-live-bind] wrote ${file}`);
  return { args: ['--extension', file], cleanup: file };
}

function removeBindingExtension(file, log) {
  if (!file) return;
  try { fs.rmSync(file, { force: true }); }
  catch (err) { if (log && typeof log.warn === 'function') log.warn(`[pi-live-bind] cleanup failed: ${err.message}`); }
}

module.exports = { writeBindingExtension, removeBindingExtension };
