// Pi live binding through a per-spawn extension.
//
// Pi owns its session id and can switch it in-place (/new, /resume, /fork). The core already has a
// backend-neutral terminal binding URL for "terminal <tag> is now on session <id>" (#303); this adapter
// writes a tiny Pi extension that posts that fact on session lifecycle events. Pi-specific event names and
// ctx.sessionManager access stay here, under the backend descriptor.
'use strict';

const fs = require('fs');
const path = require('path');

function jsString(value) {
  return JSON.stringify(String(value || ''));
}

function writeBindingExtension({ dir, tag, sessionUrl, log } = {}) {
  if (!dir || !tag || !sessionUrl) return null;
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `pi-live-${tag}.ts`);
  const source = `// Generated by Switchboard for one Pi spawn. Safe to delete.\n` +
`import type { ExtensionAPI } from \"@earendil-works/pi-coding-agent\";\n\n` +
`const URL = ${jsString(sessionUrl)};\n\n` +
`async function post(ctx: any, kind?: \"busy\" | \"idle\") {\n` +
`  const id = ctx?.sessionManager?.getSessionId?.();\n` +
`  if (!id) return;\n` +
`  try {\n` +
`    await fetch(URL, {\n` +
`      method: \"POST\",\n` +
`      headers: { \"content-type\": \"application/json\" },\n` +
`      body: JSON.stringify({ session_id: id, kind }),\n` +
`    });\n` +
`  } catch {}\n` +
`}\n\n` +
`export default function(pi: ExtensionAPI) {\n` +
`  pi.on(\"session_start\", async (_event, ctx) => { await post(ctx); });\n` +
`  pi.on(\"turn_start\", async (_event, ctx) => { await post(ctx, \"busy\"); });\n` +
`  pi.on(\"turn_end\", async (_event, ctx) => { await post(ctx, \"idle\"); });\n` +
`  pi.on(\"agent_settled\", async (_event, ctx) => { await post(ctx, \"idle\"); });\n` +
`  pi.on(\"session_info_changed\", async (_event, ctx) => { await post(ctx); });\n` +
`}\n`;
  fs.writeFileSync(file, source, 'utf8');
  if (log && typeof log.debug === 'function') log.debug(`[pi-live-bind] wrote ${file}`);
  return { args: ['--extension', file], cleanup: file };
}

function removeBindingExtension(file, log) {
  if (!file) return;
  try { fs.rmSync(file, { force: true }); }
  catch (err) { if (log && typeof log.warn === 'function') log.warn(`[pi-live-bind] cleanup failed: ${err.message}`); }
}

module.exports = { writeBindingExtension, removeBindingExtension };
