'use strict';
// The two prompt templates the app ships for Pi (#569).
//
// Like the live-binding extension beside it, nothing in this tree executes what this file produces — and
// nothing reads it back either. Each spawn gets a directory of its own, handed over as
// `--prompt-template`, and Pi reads what is in it in its own process; a template it refuses simply does
// not appear as a command. So the assertions below are written against Pi 0.84.4's own reader —
// `parseFrontmatter` in `dist/utils/frontmatter.js` and `substituteArgs` in
// `dist/core/prompt-templates.js` — and each one names the behaviour it is standing in for.
//
// Three of those assertions are about something no shape test can reach. The frontmatter block has to be
// valid YAML, because Pi's `loadTemplateFromFile` swallows a parse error in a bare `catch` and the
// command then does not exist, with no diagnostic in Pi and none here either — so the block is handed to
// a real parser below rather than matched with a regex. The note in that block is pinned BY VALUE, for
// the same reason the module's header gives for writing a fixed sentence: a value that grows a path, a
// name or anything else a user supplies is one failed quote away from the same silent loss. And the BODY
// has to carry the two conventions `docs/handoffs-convention.md` and `docs/plans-convention.md`
// describe, because a body rewritten to say nothing about either one is still a perfectly well-formed
// template that teaches the agent nothing.

const test = require('node:test');
const assert = require('node:assert/strict');
// The parser Pi uses for its own frontmatter. Asking it here is not circular: the question is whether the
// COMPOSED text parses, and the composer never parses anything.
const jsYaml = require('js-yaml');

const {
  KINDS,
  buildPromptTemplate,
  hasArgumentSubstitution,
} = require('../src/backends/pi/prompt-templates');

// Pi's frontmatter bounds, reimplemented here rather than imported: Pi is not a dependency of this app,
// and a test that only asks our own parser whether our own output parses proves nothing. This answers
// WHERE the block ends; whether what is inside it loads is the separate question below.
function splitLikePi(text) {
  const normalized = text.replace(/^﻿/, '').replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  if (!normalized.startsWith('---')) return { yaml: null, body: normalized };
  const end = normalized.indexOf('\n---', 3);
  if (end === -1) return { yaml: null, body: normalized };
  return { yaml: normalized.slice(4, end), body: normalized.slice(end + 4).trim() };
}

// Pi's substitution regex, verbatim from `substituteArgs`.
const PI_SUBSTITUTION = /\$\{(\d+|ARGUMENTS|@):-([^}]*)\}|\$\{@:(\d+)(?::(\d+))?\}|\$(ARGUMENTS|@|\d+)/g;

// Every key the composed frontmatter may hold. Pi reads the first two and ignores the rest; the other
// two are a label and a note about where a file came from, not a contract anything reads back. Written as
// an exhaustive set rather than a "must contain", because a key added here is a line inside a block
// somebody else's parser loads, and one that does not parse costs the whole command.
const FRONTMATTER_KEYS = [
  'description',
  'argument-hint',
  'x-switchboard-template',
  'x-switchboard-note',
];

// The note, verbatim. It is a fixed sentence and must stay one: every value in this block is written into
// YAML that Pi throws the whole template away over if it fails to parse, inside a bare `catch` and with
// no diagnostic anywhere, so a note carrying a directory name, a project name or anything else somebody
// typed is a command that silently stops existing.
const NOTE_TEXT = 'Generated by Switchboard for one Pi session. Safe to delete.';

// The header fields `docs/handoffs-convention.md` gives a packet under "What a handoff looks like", and
// the sections the app's own packets carry. Both halves are the convention, not the current wording: a
// body that stops naming them is a body that no longer describes a handoff anybody else can read.
const HANDOFF_HEADER_FIELDS = ['created', 'backend'];
const HANDOFF_SECTIONS = [
  'Goal',
  'Completed',
  'In progress',
  'Blocked or risky',
  'Important files/context',
  'Next actions',
  'Avoid',
];

// The header block `docs/plans-convention.md` describes, and every status it lists. The status set is
// the part with teeth: a plan whose status is not one of these four cannot be scanned by the app or by
// the person reading the directory, and dropping one of them from the prompt is invisible until a plan
// turns up carrying something else.
const PLAN_HEADER_FIELDS = ['status', 'updated'];
const PLAN_STATUSES = ['active', 'done', 'superseded', 'blocked'];

// The `> …` line of a composed body's header block, or undefined when the body has stopped showing one.
function headerLineOf(body) {
  return body.split('\n').find((line) => line.trim().startsWith('> '));
}

test('both kinds compose, and the command is the file name', () => {
  assert.deepEqual(KINDS, ['handoff', 'plan']);
  for (const kind of KINDS) {
    const built = buildPromptTemplate(kind, '.docs-dir');
    assert.equal(built.ok, true, `${kind}: composed nothing`);
    assert.equal(built.kind, kind);
    assert.equal(built.fileName, `${kind}.md`);
    assert.equal(built.command, `/${kind}`);
  }
});

test('Pi finds a description and an argument hint where it looks for them', () => {
  for (const kind of KINDS) {
    const { yaml } = splitLikePi(buildPromptTemplate(kind, '.docs-dir').text);
    assert.ok(yaml, `${kind}: Pi found no frontmatter block at all`);
    // Both keys quoted, because invalid YAML makes Pi's loader return null inside a bare catch — the
    // command would vanish with no diagnostic anywhere.
    assert.match(yaml, /^description: ".+"$/m);
    assert.match(yaml, /^argument-hint: ".+"$/m);
  }
});

test('the frontmatter is real YAML and holds exactly the keys it is allowed to hold', () => {
  for (const kind of KINDS) {
    const { yaml } = splitLikePi(buildPromptTemplate(kind, '.docs-dir').text);
    let parsed;
    // This is the failure the module's header calls fatal: Pi throws the whole template away inside a
    // bare `catch`, so a block that stops parsing removes `/${kind}` with nothing said anywhere.
    assert.doesNotThrow(() => { parsed = jsYaml.load(yaml); }, `${kind}: Pi would discard this template`);
    assert.equal(typeof parsed, 'object');
    assert.deepEqual(Object.keys(parsed).sort(), [...FRONTMATTER_KEYS].sort());
    // Unquoted, `[what to focus on]` is a YAML flow sequence and Pi shows the hint as `[object Object]`
    // or nothing at all. The brackets have to survive the parse as part of a string.
    const hint = parsed['argument-hint'];
    assert.equal(typeof hint, 'string', `${kind}: the argument hint did not parse as a string`);
    assert.match(hint, /^\[.+\]$/, `${kind}: the hint lost its brackets on the way through YAML`);
    assert.equal(typeof parsed.description, 'string');
    assert.ok(parsed.description.length > 0, `${kind}: Pi would list this command with no description`);
    assert.equal(parsed['x-switchboard-template'], kind);
    // By value, not by shape: nothing in this block may be dynamic or user-supplied.
    assert.equal(parsed['x-switchboard-note'], NOTE_TEXT, `${kind}: the note is no longer a fixed sentence`);
  }
});

test('the directory the caller names is the one the agent is told to write to', () => {
  const handoff = buildPromptTemplate('handoff', '.packets').text;
  assert.ok(handoff.includes('markdown file in .packets,'));
  const plan = buildPromptTemplate('plan', 'docs/plans').text;
  assert.ok(plan.includes('markdown file in docs/plans,'));
});

test('a directory spelled with backslashes reaches the agent with forward slashes', () => {
  // `conventionDirs` spells a relative name with the platform separator, so an absolute setting inside
  // the project comes back as `docs\plans` on Windows. A lone backslash in prose is one typo away from
  // reading as an escape, and the two convention documents both write forward slashes.
  const built = buildPromptTemplate('plan', String.raw`docs\plans`);
  assert.equal(built.ok, true);
  assert.ok(built.text.includes('markdown file in docs/plans,'), 'the separator was not normalised');
  assert.ok(!built.text.includes(String.raw`docs\plans`), 'a backslash survived into the body');
});

test('the handoff body carries the packet shape the convention describes', () => {
  // `docs/handoffs-convention.md`, "What a handoff looks like". Typed inside Pi, this prompt is the only
  // thing that tells the agent any of it — nothing in this app reviews what comes back.
  const { body } = splitLikePi(buildPromptTemplate('handoff', '.packets').text);
  assert.match(body, /first heading/, 'the body no longer says the title is the first heading');
  assert.ok(body.includes('<date>-<slug>.md'), 'the body no longer names the file shape');
  const header = headerLineOf(body);
  assert.ok(header, 'the body shows no header block at all');
  for (const field of HANDOFF_HEADER_FIELDS) {
    assert.match(header, new RegExp(`\\b${field}:`), `the header block stopped carrying ${field}`);
  }
  for (const section of HANDOFF_SECTIONS) {
    assert.match(body, new RegExp(`^- ${section}$`, 'm'), `the packet lost its ${section} section`);
  }
});

test('the plan body carries the header block and every status the convention lists', () => {
  // `docs/plans-convention.md`, "What a plan looks like". The status set is what the app and a human
  // scanning the directory both read; a prompt that names three of the four produces plans nobody can
  // sort, and nothing else in this tree would say so.
  const { body } = splitLikePi(buildPromptTemplate('plan', '.plans').text);
  assert.match(body, /first heading/, 'the body no longer says the title is the first heading');
  assert.ok(body.includes('<date>-<slug>.md'), 'the body no longer names the file shape');
  const header = headerLineOf(body);
  assert.ok(header, 'the body shows no header block at all');
  for (const field of PLAN_HEADER_FIELDS) {
    assert.match(header, new RegExp(`\\b${field}:`), `the header block stopped carrying ${field}`);
  }
  for (const status of PLAN_STATUSES) {
    assert.match(body, new RegExp(`\\b${status}\\b`), `the body stopped offering status ${status}`);
  }
  // The convention asks a blocked plan to say what would unblock it, which is the one status that means
  // nothing on its own.
  assert.match(body, /unblock/, 'the body no longer asks a blocked plan what would unblock it');
});

test('the body ends with the argument tail, so extra guidance reaches the agent', () => {
  for (const kind of KINDS) {
    const { body } = splitLikePi(buildPromptTemplate(kind, '.docs-dir').text);
    assert.ok(body.endsWith('$@'), `${kind}: nothing would carry /${kind} <extra guidance>`);
  }
});

test('nothing else in the body is eaten by Pi argument substitution', () => {
  for (const kind of KINDS) {
    const { body } = splitLikePi(buildPromptTemplate(kind, '.docs-dir').text);
    const found = body.match(PI_SUBSTITUTION) || [];
    // Exactly the deliberate tail. A stray `$1` in prose is rewritten to the empty string and the
    // sentence silently loses a word.
    assert.deepEqual(found, ['$@'], `${kind}: unintended substitution in the body`);
  }
});

test('a directory Pi would rewrite is refused, and the refusal says which rule refused it', () => {
  // `substituteArgs` honours no backslash and no doubling, so these cannot be represented at all.
  for (const dir of ['$1plans', 'a$@b', '.plans$ARGUMENTS', '${1:-x}', '${@:2}']) {
    assert.equal(hasArgumentSubstitution(dir), true, `${dir} should be refused`);
    // The reason is the whole point of answering an object: the one caller puts a sentence in front of
    // the user and must not have to re-derive which rule said no.
    assert.deepEqual(buildPromptTemplate('plan', dir), { ok: false, reason: 'argument-substitution' });
  }
  // A lone `$` is not a substitution — Pi's regex needs a digit, `@`, `ARGUMENTS` or `{` after it.
  assert.equal(hasArgumentSubstitution('.plans$'), false);
  assert.equal(buildPromptTemplate('plan', '.plans$').ok, true);
});

test('an empty directory and an unknown kind are refused, each under its own reason', () => {
  for (const dir of ['', '   ', null, undefined]) {
    assert.deepEqual(buildPromptTemplate('plan', dir), { ok: false, reason: 'no-directory' });
  }
  // A backslash-only value normalises to a directory name that is still there, so it is not this case —
  // only a name that trims away is.
  assert.deepEqual(buildPromptTemplate('nonesuch', '.plans'), { ok: false, reason: 'unknown-kind' });
  // The kind is checked first: an unknown kind with no directory still reads as the unknown kind, so a
  // caller reporting "name a directory" for a typo'd kind is impossible.
  assert.deepEqual(buildPromptTemplate('nonesuch', ''), { ok: false, reason: 'unknown-kind' });
});
