// #634 — the per-spawn `subagent` extension for Pi. What is pinned here is the WRITER: when it writes, what
// it hands the launch, what the file carries, and what the remover will and will not delete. Whether Pi
// runs the tool is a click test in the demo; nothing in this suite starts Pi.
'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const subagentTool = require('../src/backends/pi/subagent-tool');
const pi = require('../src/backends/pi');
const piNative = require('../src/backends/pi-native');

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'sb-subagent-'));
}

test('writes nothing unless the option is switched on', () => {
  const dir = tmpDir();
  try {
    for (const options of [undefined, {}, { subagentTool: false }, { subagentTool: 'true' }, { subagentTool: 1 }]) {
      assert.equal(subagentTool.writeSubagentExtension({ dir, tag: 'abc', options }), null, JSON.stringify(options));
    }
    assert.deepEqual(fs.readdirSync(dir), []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('switched on, it writes one .ts file and hands Pi --extension with it', () => {
  const dir = tmpDir();
  try {
    const built = subagentTool.writeSubagentExtension({ dir, tag: 'abc-123', options: { subagentTool: true } });
    assert.ok(built);
    assert.deepEqual(built.args, ['--extension', built.cleanup]);
    assert.equal(path.dirname(built.cleanup), dir);
    assert.equal(path.basename(built.cleanup), 'pi-subagent-abc-123.ts');
    const src = fs.readFileSync(built.cleanup, 'utf8');
    assert.match(src, /^\/\/ Generated by Switchboard for one Pi spawn\. Safe to delete\./);
    assert.match(src, /name: "subagent"/);
    // No agents directory set: the extension falls back to Pi's own.
    assert.match(src, /const AGENTS_DIR: string = "";/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the child is started the way the example measured: json mode, one prompt, no session file', () => {
  const src = subagentTool.extensionSource({});
  assert.match(src, /\["--mode", "json", "-p", "--no-session"\]/);
  assert.match(src, /--append-system-prompt/);
  // The cost reaches the result text, not only the details — that is what makes it visible in Pi's TUI
  // and in the conversation view without either knowing this tool.
  assert.match(src, /usageLine\(agent\.name, usage, usedModel\)/);
});

test('refuses a tag that is not a plain token', () => {
  const dir = tmpDir();
  try {
    for (const tag of ['../x', 'a/b', 'a\\b', '', '.hidden']) {
      assert.equal(subagentTool.writeSubagentExtension({ dir, tag, options: { subagentTool: true } }), null, tag);
    }
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the agents directory is written as a string literal, and ~ is the home directory', () => {
  const hostile = 'x"; process.exit(1); //';
  const src = subagentTool.extensionSource({ agentsDir: hostile });
  assert.ok(src.includes(`const AGENTS_DIR: string = ${JSON.stringify(hostile)};`));

  const dir = tmpDir();
  try {
    const built = subagentTool.writeSubagentExtension({
      dir, tag: 't1', options: { subagentTool: true, subagentAgentsDir: '~/agents-here' },
    });
    const text = fs.readFileSync(built.cleanup, 'utf8');
    assert.ok(text.includes(JSON.stringify(path.join(os.homedir(), 'agents-here'))));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the generated source carries no interpolation left over from this file', () => {
  // The extension body sits inside a template literal here; a `${` in it would have been evaluated by the
  // writer instead of written out, and a stray one is how that shows.
  const src = subagentTool.extensionSource({ agentsDir: '' });
  assert.ok(!src.includes('${'), 'the written extension must not contain ${');
  assert.match(src, /const OUTPUT_CAP = \d+;/);
});

test('the remover deletes only a file this module named', () => {
  const dir = tmpDir();
  try {
    const own = path.join(dir, 'pi-subagent-abc.ts');
    const other = path.join(dir, 'pi-live-abc.ts');
    fs.writeFileSync(own, 'x');
    fs.writeFileSync(other, 'x');
    subagentTool.removeSubagentExtension(other);
    subagentTool.removeSubagentExtension(dir);
    assert.ok(fs.existsSync(other));
    subagentTool.removeSubagentExtension(own);
    assert.ok(!fs.existsSync(own));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('pi declares both fields as spawn-applied and off; pi-native does not offer them yet', () => {
  const byId = Object.fromEntries(pi.configFields.map(f => [f.id, f]));
  assert.equal(byId.subagentTool.default, false);
  assert.equal(byId.subagentTool.appliedBy, 'buildSubagentTool');
  assert.equal(byId.subagentAgentsDir.appliedBy, 'buildSubagentTool');
  assert.equal(byId.subagentAgentsDir.requires, 'subagentTool');
  // Step 1 of #634: the native backend's approval gate does not yet see a child's calls, so it neither
  // shows the fields nor carries the hooks. Step 2 lifts both together.
  const nativeIds = piNative.configFields.map(f => f.id);
  assert.ok(!nativeIds.includes('subagentTool'));
  assert.ok(!nativeIds.includes('subagentAgentsDir'));
  assert.notEqual(piNative.providesSubagentTool, true);
});
