// #634 — the `subagent` tool for Pi. What is pinned here is the WRITER: when it writes, what it hands the
// launch, what the file carries, and what the remover will and will not delete. Whether Pi runs the tool is
// a click test in the demo; nothing in this suite starts Pi.
//
// Since #632 (owner decision O5) the tool is a SECTION of the one per-spawn resources extension
// (`src/backends/pi/resources-extension.js`), written through `buildSessionResources`. The writer questions
// are asked of that hook; the tool's own text is still `subagentTool.extensionSource`.
'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const subagentTool = require('../src/backends/pi/subagent-tool');
const resourcesExtension = require('../src/backends/pi/resources-extension');
const pi = require('../src/backends/pi');
const piNative = require('../src/backends/pi-native');

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'sb-subagent-'));
}

test('writes nothing unless the option is switched on', () => {
  const dir = tmpDir();
  try {
    for (const options of [undefined, {}, { subagentTool: false }, { subagentTool: 'true' }, { subagentTool: 1 }]) {
      assert.equal(pi.buildSessionResources({ dir, tag: 'abc', options }), null, JSON.stringify(options));
    }
    assert.deepEqual(fs.readdirSync(dir), []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('switched on, it writes one .ts file and hands Pi --extension with it', () => {
  const dir = tmpDir();
  try {
    const built = pi.buildSessionResources({ dir, tag: 'abc-123', options: { subagentTool: true } });
    assert.ok(built);
    assert.deepEqual(built.args, ['--extension', built.cleanup]);
    assert.equal(built.subagent, true);
    assert.equal(path.dirname(built.cleanup), dir);
    assert.equal(path.basename(built.cleanup), 'pi-resources-abc-123.ts');
    const src = fs.readFileSync(built.cleanup, 'utf8');
    assert.match(src, /^\/\/ Generated by Switchboard for one Pi spawn\. Safe to delete\./);
    assert.match(src, /name: "subagent"/);
    assert.match(src, /registerSubagent\(pi\);/);
    // No agents directory set: the extension falls back to Pi's own.
    assert.match(src, /const AGENTS_DIR: string = "";/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the child is started the way the example measured: json mode, one prompt, no session file', () => {
  const src = subagentTool.extensionSource({});
  assert.match(src, /\["--mode", "json", "-p", "--no-session"\]/);
  assert.match(src, /--append-system-prompt/);
  // The cost reaches the result text, not only the details — that is what makes it visible in Pi's TUI
  // and in the conversation view without either knowing this tool.
  assert.match(src, /usageLine\(agent\.name, usage, usedModel\)/);
});

test('refuses a tag that is not a plain token', () => {
  const dir = tmpDir();
  try {
    for (const tag of ['../x', 'a/b', 'a\\b', '', '.hidden']) {
      assert.equal(pi.buildSessionResources({ dir, tag, options: { subagentTool: true } }), null, tag);
    }
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the agents directory is written as a string literal, and ~ is the home directory', () => {
  const hostile = 'x"; process.exit(1); //';
  const src = subagentTool.extensionSource({ agentsDir: hostile });
  assert.ok(src.includes(`const AGENTS_DIR: string = ${JSON.stringify(hostile)};`));

  const dir = tmpDir();
  try {
    const built = pi.buildSessionResources({
      dir, tag: 't1', options: { subagentTool: true, subagentAgentsDir: '~/agents-here' },
    });
    const text = fs.readFileSync(built.cleanup, 'utf8');
    assert.ok(text.includes(JSON.stringify(path.join(os.homedir(), 'agents-here'))));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('the generated source carries no interpolation left over from this file', () => {
  // The extension body sits inside a template literal here; a `${` in it would have been evaluated by the
  // writer instead of written out, and a stray one is how that shows.
  const src = subagentTool.extensionSource({ agentsDir: '' });
  assert.ok(!src.includes('${'), 'the written extension must not contain ${');
  assert.match(src, /const OUTPUT_CAP = \d+;/);
});

test('the remover deletes only a file this module named', () => {
  const dir = tmpDir();
  try {
    const own = path.join(dir, 'pi-resources-abc.ts');
    const other = path.join(dir, 'pi-live-abc.ts');
    fs.writeFileSync(own, 'x');
    fs.writeFileSync(other, 'x');
    pi.releaseSessionResources(other);
    pi.releaseSessionResources(dir);
    assert.ok(fs.existsSync(other));
    pi.releaseSessionResources(own);
    assert.ok(!fs.existsSync(own));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('pi declares both fields as spawn-applied and off', () => {
  const byId = Object.fromEntries(pi.configFields.map(f => [f.id, f]));
  assert.equal(byId.subagentTool.default, false);
  assert.equal(byId.subagentTool.appliedBy, 'buildSessionResources');
  assert.equal(byId.subagentAgentsDir.appliedBy, 'buildSessionResources');
  assert.equal(byId.subagentAgentsDir.requires, 'subagentTool');
});

test('the tool on its own and the tool as a section of the resources extension are the same code', () => {
  const alone = subagentTool.extensionSource({ agentsDir: 'x' });
  const merged = resourcesExtension.extensionSource({ subagent: { agentsDir: 'x' } });
  assert.ok(alone.includes(subagentTool.subagentSection({ agentsDir: 'x' })));
  assert.ok(merged.includes(subagentTool.subagentSection({ agentsDir: 'x' })));
  // Imports merged: one line per module, however many sections name it.
  for (const text of [alone, merged]) {
    assert.equal((text.match(/from "node:fs";/g) || []).length, 1);
  }
});

// Step 2 of #634. The native backend offers the tool only together with a question about it: its child is a
// second Pi without the runtime extension, so the delegation is the one call the gate can ever see. The
// fields, the hooks and the gated name travel as one — a control without the question is what this pins.
test('pi-native offers the tool, and its approval gate asks about every delegation', () => {
  const nativeIds = piNative.configFields.map(f => f.id);
  assert.ok(nativeIds.includes('subagentTool'));
  assert.ok(nativeIds.includes('subagentAgentsDir'));
  assert.equal(piNative.providesSessionResources, true);
  assert.equal(piNative.buildSessionResources, pi.buildSessionResources);
  assert.equal(piNative.releaseSessionResources, pi.releaseSessionResources);

  const runtimeExtension = require('../src/backends/pi-native/runtime-extension');
  assert.ok(runtimeExtension.GATED_TOOLS.includes('subagent'));
  // The tool's own name, spelled once in the generated extension; the gate must name the same one.
  assert.match(subagentTool.extensionSource({}), /name: "subagent"/);
});

// F1 of the step-2 review: the question about a delegation says what the agent may do. The subagent extension
// publishes a describer under a registry symbol and the gate reads the same key — both generated sources have
// to spell it, or the question silently goes without the line.
test('the delegation question carries the agent description through the approval title', () => {
  const runtimeExtension = require('../src/backends/pi-native/runtime-extension');
  const key = JSON.stringify(subagentTool.DESCRIBE_KEY);
  assert.ok(subagentTool.extensionSource({}).includes(`Symbol.for(${key})] = describeAgent`));
  assert.ok(runtimeExtension.extensionSource({ gate: true }).includes(`Symbol.for(${key})]`));

  const title = runtimeExtension.APPROVAL_PREFIX
    + JSON.stringify({ tool: 'subagent', id: 'c1', detail: 'Agent counter · tools: ls, read\n· model: x' });
  assert.deepEqual(runtimeExtension.parseApprovalTitle(title),
    { tool: 'subagent', id: 'c1', detail: 'Agent counter · tools: ls, read · model: x', by: '' });
  // An old-shape title (no detail) still parses, with an empty line rather than a missing field.
  assert.deepEqual(runtimeExtension.parseApprovalTitle(runtimeExtension.APPROVAL_PREFIX + '{"tool":"bash","id":"c2"}'),
    { tool: 'bash', id: 'c2', detail: '', by: '' });
  // …and it is held to one capped line.
  const long = runtimeExtension.parseApprovalTitle(runtimeExtension.APPROVAL_PREFIX
    + JSON.stringify({ tool: 'subagent', id: 'c3', detail: 'x'.repeat(5000) }));
  assert.ok(long.detail.length <= 400);
});

test('the approvalGate setting says it asks before a subagent run', () => {
  const gate = piNative.configFields.find(f => f.id === 'approvalGate');
  assert.match(gate.description, /subagent/);
});
