// A session can be rendered as MORE THAN ONE row (#289): the lineage thread lists a head's whole ancestor
// chain (#193), so a session that also has its own top-level row appears twice. `querySelector` takes the
// first match in document order — which can be the copy — so a state write landed on the wrong row and the
// real one stayed stale until the next full render.
//
// Nothing loads app.js in a test (it is the composition root of the renderer), so this is a SOURCE guard:
// no renderer file may look a session row up single-target again. The two helpers say which one they mean —
// `sessionRowEls` (every row of the session) and `canonicalSessionRow` (the one that is not a copy).
'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const REN = path.join(__dirname, '..', 'src', 'renderer');

function rendererFiles(dir = REN, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) rendererFiles(p, out);
    // codemirror-bundle.js is generated by esbuild and is not ours to hold to this rule.
    else if (e.name.endsWith('.js') && e.name !== 'codemirror-bundle.js') out.push(p);
  }
  return out;
}

test('no renderer file looks a session row up single-target', () => {
  const offenders = [];
  for (const file of rendererFiles()) {
    const src = fs.readFileSync(file, 'utf8');
    src.split('\n').forEach((line, i) => {
      if (!/\.querySelector\(\s*[`'"][^`'"]*data-session-id/.test(line)) return;
      // The canonical lookup is the one legitimate single-target read: it excludes the copies by selector.
      if (line.includes(':not([data-ancestor-copy])')) return;
      offenders.push(`${path.relative(REN, file)}:${i + 1}`);
    });
  }
  assert.deepEqual(offenders, [],
    'use sessionRowEls(id) for state that belongs to the session, canonicalSessionRow(id) for navigation');
});

test('the helpers exist in app.js and take an optional root', () => {
  const src = fs.readFileSync(path.join(REN, 'app.js'), 'utf8');
  // The sidebar applies state to the DETACHED tree it is about to morph in, so the root is not optional
  // in practice — a helper hard-wired to `document` would silently do nothing there.
  assert.match(src, /function sessionRowEls\(sessionId, root = document\)/);
  assert.match(src, /function canonicalSessionRow\(sessionId, root = document\)/);
});

test('the dead timeago interval is gone', () => {
  // It refreshed `.session-meta-text` every 30 s; no builder has produced that element for some time, so it
  // walked the whole activity map twice a minute and updated nothing.
  const src = fs.readFileSync(path.join(REN, 'app.js'), 'utf8');
  assert.equal(src.includes('session-meta-text'), false);
  const builders = ['shell/sidebar-session-row.js', 'shell/sidebar-subagents.js'];
  for (const rel of builders) {
    assert.equal(fs.readFileSync(path.join(REN, rel), 'utf8').includes('session-meta-text'), false,
      `${rel} still does not create it — revive the interval only together with the element`);
  }
});
